#!/usr/bin/env bash

###
# Setting up vars
#
# JSLINTR_ROOT=/opt/local/lib/jslint/
# OPTIONS_FILE=/opt/local/etc/options.sample
#
export JSLINTR_ROOT=${JSLINTR_ROOT:-$(pwd -P)}
export JSLINTR_LIB="$JSLINTR_ROOT/lib/"
OPTIONS_SAMPLE_FILE="${JSLINTR_ROOT}/etc/options.sample"

FIND=find
EGREP=egrep
PWD=pwd
CHMOD=chmod

###
# Adding start_jslintr function
#
source "$JSLINTR_LIB/start_jslintr"
	
###
# Verifying optional parameters
#
case "$1" in 
	"-v" | "--verbose")		shift
							VERBOSE=1
							;;
	*)						VERBOSE=0
							;;
esac

###
# Verifying usage and calling jslintr =)
#		
TARGET=$1
OPTIONS_FILE=$2
OPTIONS_FILE=${OPTIONS_FILE:-$OPTIONS_SAMPLE_FILE}
OPTIONS=""
TARGET_TYPE="file"
#GOOD_PARTS='sloppy:false,white:false,nomen:true,debug:false,plusplus:true,eqeqeq:true,bitwise:true,onevar:true'

if [ "$TARGET" == "" ]; then
	echo "usage: jslintr [-v] target_path "
else
	FILE=$(file -b $TARGET)
	if [ "$FILE" == "directory" ]; then
		# removing a possible final bar
		TARGET="$(echo $TARGET | sed 's/\/$//g')"
		TARGET_TYPE="directory"		
	fi
	
	if [ -r "$OPTIONS_FILE" ]; then
		OPTIONS=$(cat $OPTIONS_FILE | xargs echo | sed 's/ //g')
	fi
	
	#echo "debug: start_jslintr $TARGET $TARGET_TYPE $VERBOSE $OPTIONS"
	start_jslintr "$TARGET" "$TARGET_TYPE" "$VERBOSE" "$OPTIONS"
fi