#!/usr/bin/env bash

###
# Setting up bins
#
FIND=find
EGREP=egrep
PWD=pwd
CHMOD=chmod

#export JSLINTR_ROOT="/usr/lib/jslintr/"
THIS_FILE=$(ls -l $0 | awk '{print $11}')
export JSLINTR_ROOT=$(dirname $THIS_FILE)
CORE="$JSLINTR_ROOT/core"

###
# Main function
#
function start_jslintr () {
	DIR=${1}
	SRCROOT=${DIR:-LOCALDIR}
		
    echo -e "\n====+> Starting JSLint. \n\n    \"WARNING! JSLint will hurt your feelings.\" - Douglas Crockford \n"

    counter=0
    for JS_FILE in $( ${FIND} ${SRCROOT} -type f -name '*.js' | ${EGREP} -v '\.svn' );
    do
		#echo "debug:: ${CORE} "${JS_FILE}" ${VERBOSE_MODE}"
        counter=$(($counter+1));
		JS_FILE="$(echo $JS_FILE | sed 's/\/\//\//g')" # substituting // in /js	
  	    ${CORE} "${JS_FILE}" ${VERBOSE_MODE};
    done

    echo -e "\n\n===+> JSLintr Complete: ${counter} tests done! \n"
}

	
###
# Verifying optionals
#

if [ "$1" == "-v" ]; then
	shift # shifting parameters index
	export VERBOSE_MODE=1
else
	export VERBOSE_MODE=0
fi

if [ "$1" == "" ]; then
	echo "usage: jslintr [-v] /directory/name/ "
else
	TYPE=$(file -b $1)
	if [ $TYPE == "directory" ]; then
		DIR="$(echo $1 | sed 's/\/\//\//g')" # substituting // in /
	fi
		
	#echo "debug:: start_jslintr $DIR"
	start_jslintr "$DIR"
fi