#!/usr/bin/env bash

FILE_NAME=${1}
VERBOSE_MODE=${2}
VERBOSE=${VERBOSE_MODE:-1}

SRCROOT=${SRCROOT:-./}

MKTEMP=${MKTEMP:-/usr/bin/mktemp}
SED=${MKTEMP:-/usr/bin/sed}

RHINO=bin/js.jar
JSLINTR=bin/jslintr.js
JSLINT=bin/jslint.js

OPTIONS='sloppy: true, white:false, nomen:true, debug:false, plusplus:true, eqeqeq:true, bitwise:true, onevar:true'

GREEN="\e[0;32m"
RED="\e[0;31m"
NC="\e[0m"

function has_jslint_errors () {
  LINTRESULTS="${1}"

  JSLINT_INDEX=$(expr "$LINTRESULTS" : "OK")

  if [ "$JSLINT_INDEX" -eq 0 ]
  then 
      return 0
  else
      return 1
  fi 
}

function verbose_output () {
  # naming parameters
  FILENAME="${1}"
  LINTRESULTS="${2}"

  if has_jslint_errors "$LINTRESULTS"
  then
      RESULT="${RED}FAIL${NC} - $LINTRESULTS\n\n"
  else
      RESULT="${GREEN}OK${NC}\n"
  fi

  printf "${FILENAME}: ${RESULT}"
}

function concise_output () {
  # naming parameters
  FILENAME="${1}"
  LINTRESULTS="${2}"

  if has_jslint_errors "$LINTRESULTS"
  then
      RESULT="${RED}FAIL${NC} at ${FILENAME} - $LINTRESULTS\n\n"
  else
      RESULT="${GREEN}.${NC}"
  fi

  printf "${RESULT}"
}

function runjslint () {
  # naming parameters
  TO_ANALYZE="${1}"
  REALFNAME="${2}"

  #LINT_RESULT=$(java -jar ${RHINO} ${JSLINT} "${TOANALYZE}" | ${SED} "s,${TOANALYZE},${REALFNAME},")
  LINT_RESULT=$(java -jar ${RHINO} -f ${JSLINT} ${JSLINTR} ${TO_ANALYZE})

  #echo "${LINT_RESULT}"
  FNAME=$REALFNAME

  #FILENAME_TRASH="${PWD}"
  #POS=$(expr match "$REALFNAME" "'"${FILENAME_TRASH}"'")
  #echo "pos: $POS"
  #FNAME=".${REALFNAME:$POS}"
  #echo "FNAME: ${FNAME}"


  if [ "$VERBOSE" -eq 0 ]
  then
      concise_output "${FNAME}" "${LINT_RESULT}"
  else
      verbose_output "${FNAME}" "${LINT_RESULT}"
  fi
}

TEMPFILE=$(${MKTEMP} /tmp/jslint.XXXXXXXXXX) && {
  echo "/*jslint ${OPTIONS} */" > "${TEMPFILE}"
  /bin/cat "${FILE_NAME}" >> "${TEMPFILE}"
  #echo "java -jar ${RHINO} -f ${JSLINT} ${JSLINTR} ${TEMPFILE}"
  #OUT=$(java -jar ${RHINO} -f ${JSLINT} ${JSLINTR} ${TEMPFILE})
  #echo "${OUT}"
  runjslint "${TEMPFILE}" "${FILE_NAME}"
  #/bin/rm -f "${TEMPFILE}"
}
