#!/usr/bin/env bash

DIR=${1}

FIND=/usr/bin/find
EGREP=/usr/bin/egrep
PWD=/bin/pwd

LOCALDIR=$(${PWD})
SRCROOT=${DIR:-LOCALDIR}
CHMOD=/bin/chmod
JSLINTR=src/core

echo -e "\n====+> Starting JSLint. \n\n    \"WARNING! JSLint will hurt your feelings.\" - Douglas Crockford \n"

counter=0
for M in $( ${FIND} ${SRCROOT} -type f -name '*.js' | ${EGREP} -v '\.svn' );\
do\
    counter=$(($counter+1));\
	 ${JSLINTR} "${M}" ${VERBOSE};\
done

echo -e "\n\n===+> JSLintr Complete: ${counter} tests done! \n"
